### PR TITLE
allow template absolute path

### PR DESCRIPTION
**Pull request by lcxfs1991**

### CODE REVIEW

**Comment by lcxfs1991** [comment]
@int64ago Please check

**Comment by int64ago** [comment]
I think you can achieve this purpose by setting proper `path` and `relPath`, so I'll close the PR, feel free to reopen it if necessary  :-)

**Comment by lcxfs1991** [comment]
Actually if we allow users to set absolute path, this is more understandable.

@int64ago

**Comment by int64ago** [comment]
The absolute path of template may lead to confusion if mixing with relative path in one project.

**Comment by lcxfs1991** [comment]
If the user use absolute path, root path won't apply. I think that is a solution.

**Comment by int64ago** [comment]
This's what makes confusion.

How about the following example:

At the top of project:

```js
app.use(views('/path/of/views', {
  // ...
}));
```

In one file:

```js
ctx.render('path/of/template');
```

In another file:

```js
ctx.render('/path/of/template');
```

It's strange and may cause bugs.

**Pull request closed without merging**
