### PR TITLE
Koa v2 middleware support

### PR DESCRIPTION
**Pull request by ifraixedes**
This PR provide a version of this module to use with Koa V2.

I've implemented in native `promises` as discussed on #52 

Because Koa v2 is still in alpha due the lack of native support for `async/await` functions in NodeJS, this PR should be merged in this repo in a new branch, rather than master, as other koa-* repos does (e.g. [koa-path-match](https://github.com/koajs/path-match/tree/v2.x)); I've sent PR to maste to show the changes, let me know if you prefer to send this PR on a new branch when you create it.

To release this version, Koa is using `@next` named version in `npm`, so people can install koa v2 middlewares just doing `npm install koa-xxxx@next`

On the other hand, I also added `eslint` and a standard configuration; I think that repos should have one and took an standard one than the one that I've usually used.

### CODE REVIEW

**Comment by tuananh** [comment]
👍

**Comment by ifraixedes** [comment]
Please, provide me feedback to know if I should do something for this PR could be merged.

Thanks.

**Comment by ianstormtaylor** [comment]
Any update on this? Would love to see Koa `2.0` support added!

**Comment by queckezz** [comment]
Thanks for the pull-request, really awesome! I'm going to merge this with `master` and keep a `v1.x` branch since `master` should always be the latest version.

**Comment by queckezz** [comment]
Alright, published as `5.0.0` or `next`

```bash
λ npm dist-tag add koa-views@5.0.0 next
+next: koa-views@5.0.0

λ npm dist-tag add koa-views@4.1.0 latest
+latest: koa-views@4.1.0
```

Hopefully I did everything correctly. Thanks again for the PR, really appreciated.

**Comment by ifraixedes** [comment]
Thanks for merging it.

@queckezz sure, I forgot to get rid of them

**Pull request merged**
