### PR TITLE
support app.context, not need middleware

### PR DESCRIPTION
**Pull request by EdwardZZZ**
support app.context, not need middleware

### CODE REVIEW

**Comment by int64ago** [comment]
Hi, thank for the PR, could you please explain why we need this feature, thanks again.

**Comment by EdwardZZZ** [comment]
Hi，The current 'koa-views' only supports the extension of the middleware form, the middleware form has a requirement on the order, but there is no requirement on the order through the extension of the app.context, and the extension form is more flexible.

**Comment by int64ago** [comment]
> the middleware form has a requirement on the order, but there is no requirement on the order through the extension of the app.context

It's the problem(or feature) of Koa, maybe it's not a good idea to handle this case in this way.

We are restrained to add a new feature, for removing a feature is hard.

**Comment by EdwardZZZ** [comment]
In fact, for the expansion of the context, Koa made clear suggestions:

https://github.com/koajs/koa/blob/6b6b0ddf7aff073e65493c6efaffab8331c0331c/docs/api/index.md#appcontext

**Comment by int64ago** [comment]
Ok, thanks for the explain, would you please do:

 - Add usage document in README
 - Make test description more meaningful, the number `2` after a sentence is strange

**Comment by EdwardZZZ** [comment]
OK

**Comment by int64ago** [comment]
Thanks, i'll release a minor version later :-)

**Comment by int64ago** [comment]
Released via `v6.3.0`

**Pull request merged**
