### PR TITLE
make consolidate engine source optional and allow configuration

### PR DESCRIPTION
**Pull request by kmohrf**
hey,

this pr makes consolidate default but configurable so it’s possible to use other engines but keep the koa-views infrastructure.

### CODE REVIEW

**Comment by kmohrf** [comment]
any thoughts @queckezz? :)

**Comment by queckezz** [comment]
Sorry for the late response. Awesome stuff, thank you!

**Comment by queckezz** [comment]
This is in `5.2.0` ✨

**Comment by kmohrf** [comment]
cool :)

**Pull request merged**
