### PR TITLE
change base to app-root-path

### PR DESCRIPTION
**Pull request by demohi**

### CODE REVIEW

**Comment by demohi** [comment]
Change base to the root path to your project by [app-root-path](https://github.com/inxilpro/node-app-root-path) 

Then, koa-views can be used in some framework based on koa, for eaxample [lark](https://github.com/larkjs/lark)

**Comment by queckezz** [comment]
I don't understand the problem that this is solving. Why shoudn't this be consumable with any framework based on koa? I personally think `app-root-path` is kind of a hack and only should be used in rare cases.

**Comment by demohi** [comment]
some demo code


## lib/views.js
```javascript
var views = require('koa-views');

exports.views = views;
```

## index.js
```javascript
var views = require('./lib/views');
app.use(views('views')); // the base in koa-views is  lib/
```

**Comment by demohi** [comment]
but this is rare cases  

I close this pr

**Comment by queckezz** [comment]
well I think this is the point of koa-subapps:

__index.js__
```js
var koa = require('koa')
var mount = require('koa-mount')
var app = koa()

app.use(mount('./lib/views')))
```

__./lib/views.js__
```js
module.exports = app()

app.use(views())
```

**Comment by demohi** [comment]
Thanks @queckezz

**Pull request closed without merging**
